import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';

import NextUIWrapper from '@/wrapper/NextUIWrapper';

const font = Mulish({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Epicure',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <NextUIWrapper>{children}</NextUIWrapper>
      </body>
    </html>
  );
}
